return {
	"folke/snacks.nvim",
	priority = 1000,
	lazy = false,
	opts = {
		animate = { enabled = true },
		bigfile = { enabled = true },
		bufdelete = { enabled = true },
		dashboard = require("plugins.snacks.dashboard"),
		explorer = { enabled = true },
		picker = require("plugins.snacks.picker"),
		indent = { enabled = true },
		git = { enabled = true },
		lazygit = { enabled = true },
		gitbrowse = { enabled = true },
		input = { enabled = true },
		notifier = { enabled = true },
		notify = { enabled = true },
		quickfile = { enabled = true },
		scope = { enabled = true },
		scroll = { enabled = true },
		win = { enabled = true },
		words = { enabled = true },
		statuscolumn = { enabled = true },
	},
	keys = require("plugins.snacks.key"),
}
